
#ifndef DrupalCon_DCSideMenuType_h
#define DrupalCon_DCSideMenuType_h

typedef NS_ENUM(int, DCMenuSection) {
  DCMENU_PROGRAM_ITEM = 0,
  DCMENU_BOFS_ITEM,
  DCMENU_SOCIAL_EVENTS_ITEM,
  DCMENU_SPEAKERS_ITEM,
  DCMENU_MYSCHEDULE_ITEM,
  DCMENU_LOCATION_ITEM,
  // DCMENU_INTERESTS_ITEM,
  DCMENU_INFO_ITEM,
  DCMENU_SIZE
};

#endif
